permalink: /:categories/:title
excerpt_separator: "\n\n"
include: [".well-known"]
exclude: [ 'Rakefile', "node_modules" ]
encoding: utf-8
show_drafts: true
unpublished: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
